name: hjetter-tech-docs

services:
  hjetter-tech-docs:
    image: gittesserakt/hjetter-tech-docs:latest
    ports:
      - "{HOST_PORT}:8080"
    environment:
      - HOST_PORT=8000
    restart: on-failure
